name: ptilab
channels:
  - conda-forge
dependencies:
  - python=3.7.8
  - ipywidgets==7.6.3
  - jupyterhub-singleuser==1.1.0
  - nbconvert==7.2.1
  - nbresuse
  - notebook==6.4.3
  - nteract_on_jupyter
  - numpy==1.21.6
  - scipy==1.4.1
  - matplotlib-base==3.4.3
  - jupyterlab==3.1.6
  - nodejs==14.17.4
  - ipympl==0.7.0
  - scikit-image==0.16.2
  - opencv==4.2.0
  - tensorflow==1.15.0
  - cython==0.29.15
  - gitpython==3.1.27
  - pandas==1.1.3
  - pip:
    - python-sofa==0.2.0
    - lckr-jupyterlab-variableinspector==3.0.9
