name: ptilab
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - jupyterlab
  - nodejs
  - ipympl
  - scikit-image
  - opencv
  - tensorflow
  - cython
  - gitpython
  - pip:
    - python-sofa